### PR TITLE
[Ruby] Fix HEREDOCs

### LINKED ISSUE #3124: [Ruby] SQL Heredoc not handled correctly
### What happened?

Having a simple SQL heredoc that is indented messes up syntax highlighting:

```ruby
def test
  sql = <<-SQL
    users.username LIKE :like OR
    users.email LIKE :like
  SQL
end
```
Screenshot from 2021-11-05 16-27-32

if the end tag is not indented, the highlighting is correct:

```ruby
def test
  sql = <<-SQL
    users.username LIKE :like OR
    users.email LIKE :like
SQL
end
```
Screenshot from 2021-11-05 16-31-36

### PR DESCRIPTION
**Pull request by deathaxe**
Fixes #3124

This commit...

1. embeds external syntaxes in HEREDOCs to reduce Ruby's size and to ensure terminating HEREDOC tags are matched under all circumstances.
2. improves ruby interpolation in embedded syntaxes using inheritance.

### CODE REVIEW

**Comment by michaelblyons** [comment]
Whoa! I thought you were just going to

```yaml
  heredoc-css:
    - match: <<-CSS
      scope: ...
      embed: embedded-css
      escape: ^\s*CSS

  embedded-css:
    - include: scope:source.css
    - include: embedded-ruby
    - include: escaped-chars
```

Does that not work because new line is required?

**Comment by deathaxe** [comment]
It does not work because normal ruby code may follow the HEREDOC tag up to the end of line.

File: Ruby/syntax_test_ruby.rb [hunk 1]
```diff
@@ -133,25 +133,70 @@
...
+    function test() { var local = #{@ruby_init}; }
+# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ meta.string.heredoc.ruby source.js.embedded
+#                                 ^^^^^^^^^^^^^ meta.interpolation.ruby
+  JS
+# ^^ meta.string.heredoc.ruby meta.tag.heredoc.ruby entity.name.tag.ruby
+end
+
 class_eval <<-RUBY, __FILE__, __LINE__ + 1
   def #{sym}(*args, &block)
 # ^^^^ meta.string.heredoc.ruby - meta.interpolation
```
Comment (deathaxe) [inline Ruby/syntax_test_ruby.rb:202]: Here's an example

**Review by michaelblyons — DISMISSED** [review]

**Comment by stoivo** [comment]
Pulled it locally and it works better for mee too. I will be using this going forward and report any issues I find.

**Comment by themilkman** [comment]
Might be smth. with my ST but even using exactly this branch (not merged into my usual) the JS HEREDOC does not terminate. Not even in the Syntax Test file. All others seem to work fine.

**Comment by deathaxe** [comment]
The `embed` is known to fail `escape`ing if the embedded syntax `set`s away from main branch immediately.

That's the reason why `push` is used to support shebangs in the default syntax.

https://github.com/sublimehq/Packages/blob/4adc549b9172c59fddff2cb67941fe9a6728accb/JavaScript/JavaScript.sublime-syntax#L118-L121

**Comment by deathaxe** [comment]
To clarify the the last comment:

This PR embeds ....

1. `scope:source.js.embedded.ruby` in interpolation supporting HEREDOCs, which is defined in `Embeddings/JavaScript (for Ruby).sublime-syntax and is very likely to work correctly as it inherits from builtin JavaScript syntax.
2. `scope:source.js` in literal HEREDOCs, which don't support interpolation. If a 3rd-party JavaScript syntax is installed, which `set`s away from `main` forever, the above mensioned bug is triggered. The [ECMAscript Syntax](https://packagecontrol.io/packages/Ecmascript%20Syntax) is known for that due to following lines https://github.com/bathos/Ecmascript-Sublime/blob/1d62761878518a5877371c76c8910aa0765b9402/ecmascript.sublime-syntax#L184-L194

**Review by michaelblyons — APPROVED** [review]

**Review by keith-hall — APPROVED** [review]
