### PR TITLE
[PHP] Fix SQL query concatenation 

### LINKED ISSUE #572: [PHP] SQL Syntax highlighting breaks at first appearance of matching quote
```
<?
$query_1 = "SELECT * FROM Database.dbo.test WHERE 1=1;";
$query_2 = "SELECT * FROM ".DATABASE_MAIN.".dbo.test WHERE 1=1;";
```

image

I'm not sure how feasible it would be for syntax highlighting to cover everything between the assignment operator(=) and instruction terminator(;) during an assignment but I(and my team) would greatly appreciate it.

Regardless of feasibility, thanks for an amazing product!

### PR DESCRIPTION
**Pull request by deathaxe**
Fixes #572

see: https://forum.sublimetext.com/t/color-of-sql-query-change-when-add-quotes/63178/2

This commit adds support for highlighting sql queries in all parts of a chained string.

```
$sql = "SELECT " . $col . " FROM " . $table . " WHERE foo is " . $bar ;
```

grafik

_Note: This PR may cause some conflicts with #3046. Depending on which one is merged first, we might need to tweak the one or the other slighly afterwards._

### CODE REVIEW

File: PHP/tests/syntax_test_php.php [hunk 1]
```diff
@@ -1750,6 +1783,37 @@ function generate2()
 ';
 // <- meta.string.php string.quoted.single.php punctuation.definition.string.end.php - meta.interpolation - string string
 
+$sql = 'SELECT ' . $col . 'FROM table WHERE ( first_name =' . $name . ')' ; . 'GROUP BY' ;
```
Comment (jfcherng) [inline PHP/tests/syntax_test_php.php:1786]: I am a little curious about the purpose of this `;`.

```
$sql = 'SELECT ' . $col . 'FROM table WHERE ( first_name =' . $name . ')' ; . 'GROUP BY' ;
//                                                                        ^
```

**Review by keith-hall — APPROVED** [review]

File: PHP/tests/syntax_test_php.php (hunk 1 above)
Comment (deathaxe) [reply PHP/tests/syntax_test_php.php:1786]: It is to illustrate SQL highlighting stops on expression/statement boundaries.

Comment (deathaxe) [reply PHP/tests/syntax_test_php.php:1786]: We could also add tests with concated strings in parens etc.

**Review by jfcherng — APPROVED** [review]

**Comment by michaelblyons** [comment]
Wild.

**Comment by FichteFoll** [comment]
I can practicall *feel* the SQL injection over here.
