### PR TITLE
[Perl] Feature Update 2019

### LINKED ISSUE #1029: Perl highlighting issue in regexp
`r` at the end of the regexp is causing following text to wrongly highlight. If removed, it's OK.
```perl
if (get_var('REPO_0')) {
     my $sles_debug_repo = get_var('REPO_0') =~ s/(Server|Desktop)/\U$1\E/r;
     $sles_debug_repo =~ s/DVD/POOL/;
 ```
image

### LINKED ISSUE #1325: Perl highlighting issue in regexp with newer (perl 5.20) modifiers
It seems that a lot of the new modifiers in the perl regex are not supported. Like /p, /xx, /a, /d, /l, /u, /n, /r

When using one of those in a perl regex it will break any code highlighting after this regex.

Also simple match =~ // highlighting seems to be a bit broken

Below compare shot between vim and Sublime Text 3 built 3143

screen shot 2017-11-24 at 14 28 05
screen shot 2017-11-24 at 14 28 14

### LINKED ISSUE #1326: Perl variable highlighting with variables that start with an _ (underscore) is broken
Variables that are named $foo are ok, but if they are named $_foo they do not highlight correctly. This is also the case for @ or % arrays/hashes.

compare screenshot between vim and Sublime Text 3 built 3143

screen shot 2017-11-24 at 14 30 26
screen shot 2017-11-24 at 14 30 31

### LINKED ISSUE #1495: Perl. Syntax highlight. // operator as a comment
After // operator all lines is highlighted as comment.
Version 3.0 3143

### LINKED ISSUE #2017: HIghtlight problem when prefix derefference for Perl
For the code from #1495 
```
sub x {
  my( $c ) =  shift;
  my $ctrl =  $c->stash->{ control } //=  {};
  my $id = scalar keys %{ $ctrl->{ hello } };
}
```

One problem is left for `%{ ... }` syntax:

`Modern Perl` syntax highlight OK:

PS. this is Color scheme -> legacy -> Espresso libre

### PR DESCRIPTION
**Pull request by deathaxe**
Fixes #1325 (already fixed in 3207)
Fixes #1326 (already fixed in 3207)
Fixes #1029 (already fixed in 3207)
Fixes #1495 (already fixed in 3207)
Fixes #2017

## Preamble

I know the PR is way too big again. Wouldn't have expected this amount of changes at all, when I started to think about implementing string interpolation in spring. But the latest perldocs, further investigations about the Perl interpreter itself, comparison with _ModernPerl_ and some discussions in the forum and issue #2017 revealed a number of short commings with the current implementation, which prevented correct interpolation support. The assumptions about how functions and variables are identified are just not accurate enough and the resulting implementation too "simple" to match them all correctly. Need a little bit more context sensitive scoping to accomblish better results.

## Main Goals

This PR therefore includes all required changes and fixes to accomblish the following main goals:

1. Correctly scope unqualified and qualified case insensitive function identifiers and variables properly (including `meta.path` and `variable.namespace` scopes as a suggestion resulting from #1842).
All the different expressions were therefore tested against the Perl interpreter to make sure the added syntax test cases are correct.
2. Add support for string interpolation including `meta.string.perl meta.interpolation.perl` and clearing the `string` scope.
3. Improve the scoping of referencing and dereferencing operators and add missing `\` and `&`. 

## Fixes

- some comparison expressions were matched as angular quoted strings 
- qualified identifiers must not contain whitespace
- sub routine definitions can contain attributes like `sub name :codeattribute ...`
- sub routine parameter lists consist of `type keywords` like `$`, `@`, ... only. No names allowed.
- the `%` modulo operator was not scoped
- escaping from some regular expressions in like `s/pattern\\/` failed due to the `\\`.
- scoping the deprecated tab indention in POD comments as `invalid.deprecated` was somehow annoying.

## Benchmarks

The overall performance impact of the changes is negligible, except parsing of code with many interpolated strings increases depending on the number of interpolated variables.

The benchmark file which was used to check performance impact of all the changes contains many interpolated strings. The overall parsing time increased by about 15% but it is still only 20% of the time which is needed with _ModernPerl_.

## Known issues

The usage of the _Regular Expressions_ package prevents proper matching of interpolated variables in regulare expressions. Fixing it means implementing new regexp syntax for Perl.

## Notes

This PR includes #2032 and #2036 for technical reasons. I leave it to @wbond to merge them first or together with this PR.

### CODE REVIEW

File: Perl/syntax_test_perl.pl [hunk 1]
```diff
@@ -1214,470 +2103,2419 @@ =head1 B<--param>
...
+#             ^ punctuation.definition.string.end.perl
+#              ^ punctuation.terminator.statement.perl
+  $foo{bar}
+# ^^^^ variable.other.readwrite.perl
+# ^ punctuation.definition.variable.perl
+#     ^ punctuation.section.item-access.begin.perl
+#     ^^^^^ meta.item-access.perl
+#      ^^^ constant.other.key.perl
+#         ^ punctuation.section.item-access.end.perl
+  $foo{bar()}
```
Comment (michaelblyons) [inline Perl/syntax_test_perl.pl]: I think `bar()` should also have `meta.function-call.perl` so that the hover popup where `bar` is defined can find the places it is used.

Comment (deathaxe) [reply Perl/syntax_test_perl.pl]: I think, I can re-add the `meta.function-call` to the function identifier, but it is not possible for the whole expression including the arguments list, because HEREDOCs can be passed as an argument and would cause the `meta.function-call` to never end.
