### PR TITLE
[PHP] fix docblock comments that transition to normal comments

### LINKED ISSUE #1378: [PHP] Syntax Highlight issue for multi-line asterisk comments
When creating a comment in PHP with this syntax, the highlighter "breaks" rest of the file.

***Not working***
```<?php
/**
 * PHP comment
 *
 * @see
 * @author
 * @package
 * @version
 NOTE: Modified */
```  

The issue lies in the last sentence **NOTE: Modified** which does not begins with a asterisk (*) and thus breaks the syntax highlight.

***Working***
```<?php
/**
 * PHP comment
 *
 * @see
 * @author
 * @package
 * @version
 * NOTE: Modified */
```

### PR DESCRIPTION
**Pull request by keith-hall**
fixes #1378

### CODE REVIEW

File: PHP/syntax_test_php.php [hunk 1]
```diff
@@ -386,6 +386,18 @@ function i(
...
  */
 
+/**
+ * PHP comment from issue #1378
+ *
+ * @see
+ * @author
+ * @package
+ * @version
+ NOTE: Modified */
```
Comment (rwols) [inline PHP/syntax_test_php.php]: Funny how GitHub fails to highlight this correctly too.

Comment (wbond) [reply PHP/syntax_test_php.php]: This is actually somewhat common as both GitHub and Sublime started from the same source syntax definitions from TextMate.
