### PR TITLE
[C#] fix null coalescing operator followed by a space

### LINKED ISSUE #4187: [C#] Space after a null-conditional element access operator causes rendering issues
### What happened?

Test code:

```cs
using System;
using System.Xml;

public class Program {
	public static int Main (string [] args)
	{
		var xml = new XmlDocument ();
		var outcome = xml.SelectSingleNode ("/whatever")?.Attributes? ["nope"];
		if (outcome is not null) {
			Console.WriteLine ("true");
		} else {
			Console.WriteLine ("false");
		}
		return 0;
	}
}
```

renders like this:

Image

Note the `else` word is rendered as a syntax error.

This is valid C#: https://dotnetfiddle.net/Q7akvD.

Removing the space after `Attributes?` makes it render correctly:

```cs
using System;
using System.Xml;

public class Program {
	public static int Main (string [] args)
	{
		var xml = new XmlDocument ();
		var outcome = xml.SelectSingleNode ("/whatever")?.Attributes?["nope"];
		if (outcome is not null) {
			Console.WriteLine ("true");
		} else {
			Console.WriteLine ("false");
		}
		return 0;
	}
}
```

### PR DESCRIPTION
**Pull request by keith-hall**
Fixes #4187

### CODE REVIEW

File: C#/tests/syntax_test_Operators.cs [hunk 1]
```diff
@@ -9,8 +9,12 @@
 Customer? first = customers?[0];
 /// <- support.type
 ///     ^ storage.type.nullable
-///                        ^^^^ meta.brackets
-///                        ^^ punctuation.section.brackets.begin
+///       ^^^^^ variable.other
+///             ^ keyword.operator.assignment.variable
+///               ^^^^^^^^^ variable.other
+///                        ^ keyword.operator.null-coalescing
```
Comment (michaelblyons) [inline C#/tests/syntax_test_Operators.cs:15]: Should there be a `- meta.brackets` here, or does that make things more complicated?

Comment (keith-hall) [reply C#/tests/syntax_test_Operators.cs]: good idea, added :slightly_smiling_face:

**Review by michaelblyons — APPROVED** [review]

**Review by jfcherng — APPROVED** [review]
